const DB_NAME='osouji-rotation';const STORE='app';const SETTINGS_KEY='settings';const RECORDS_KEY='records';
const DEFAULTS={cleaners:['江連','谷口','安達','小嶋','伊野','石島'],locations:[
{id:'flooring',name:'フローリング',area:'室内',summary:'床・廊下・階段（休憩室以外）',tools:['クイックルワイパー'],steps:['床の物を移動する','廊下・階段を含めてワイパーをかける','集めたごみを捨てる'],color:'green'},
{id:'wipe-down',name:'拭き掃除',area:'室内',summary:'棚・テーブル・手すり（1階・2階すべて）',tools:['アルコールペーパー'],steps:['棚の上を整理する','テーブルを拭く','階段と廊下の手すりを拭く'],color:'sand'},
{id:'toilet',name:'2階トイレ',area:'室内',summary:'便器・床・手洗い場を清潔に。',tools:['トイレブラシ','トイレ用洗剤','手袋'],steps:['換気する','便器と便座を洗う','手洗い場と床を拭く','備品を補充する'],color:'blue'},
{id:'office',name:'事務所 掃除機',area:'室内',summary:'買取店まで、事務所全体に掃除機をかける。',tools:['掃除機'],steps:['床の物を移動する','事務所から買取店まで掃除機をかける','コードと本体を片付ける'],color:'green'},
{id:'office-water',name:'事務所 水回り',area:'室内',summary:'シンクとウォーターサーバーを清潔に。',tools:['スポンジ','台所用洗剤','ふきん'],steps:['シンクを洗う','蛇口と周囲の水滴を拭く','サーバーの受け皿と外側を拭く'],color:'blue'},
{id:'outdoor-sweep',name:'屋外 掃き掃除・くもの巣',area:'屋外',summary:'屋外のごみ・落ち葉・くもの巣を取り除く。',tools:['外ぼうき','ちりとり','くもの巣取り'],steps:['建物まわりのごみと落ち葉を掃く','軒下や角のくもの巣を取る','集めたごみを捨てる'],color:'green'},
{id:'herbicide',name:'屋外 除草剤散布',area:'屋外',summary:'建物前の用水路から建物裏まで。',tools:['除草剤','散布器','手袋'],steps:['雨天・強風でないことを確認する','建物前の用水路から建物裏まで散布する','散布器を片付ける'],color:'green'},
{id:'breakroom',name:'休憩室 テーブル・床',area:'室内',summary:'テーブルと床を整えて、休憩しやすく。',tools:['アルコールペーパー','クイックルワイパー'],steps:['テーブル上を整理して拭く','椅子を整える','床にワイパーをかける'],color:'purple'},
{id:'breakroom-water',name:'休憩室 水回り',area:'室内',summary:'休憩室のシンクを清潔に。',tools:['スポンジ','台所用洗剤','ふきん'],steps:['シンクと排水口を洗う','蛇口を磨く','周囲の水滴を拭く'],color:'blue'},
{id:'washroom',name:'洗面台 水回り',area:'室内',summary:'洗面ボウル・蛇口・鏡をすっきり。',tools:['スポンジ','水回り用洗剤','クロス'],steps:['洗面ボウルを洗う','蛇口を磨く','鏡と周囲を拭く'],color:'blue'},
{id:'free-cleaning',name:'フリー清掃',area:'室内',summary:'窓・サッシ・埃取りなど、気づいた場所を清掃。',tools:['清掃場所に合う道具'],steps:['清掃する場所を決める','安全を確認して清掃する','実施内容を入力して記録する'],color:'sand',requiresNote:true}
]};
let state={settings:structuredClone(DEFAULTS),records:[],index:0,cleaner:DEFAULTS.cleaners[0],note:'',history:false,daily:true};
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function openDB(){return new Promise((ok,no)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function dbGet(k){const db=await openDB();return new Promise((ok,no)=>{const r=db.transaction(STORE).objectStore(STORE).get(k);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function dbSet(k,v){const db=await openDB();return new Promise((ok,no)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v,k);tx.oncomplete=()=>ok();tx.onerror=()=>no(tx.error)})}
async function dbClear(){const db=await openDB();return new Promise((ok,no)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).clear();tx.oncomplete=()=>ok();tx.onerror=()=>no(tx.error)})}
const jpISO=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date());
const jpNow=()=>new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',dateStyle:'medium',timeStyle:'short'}).format(new Date());
const jpDay=()=>new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'long',day:'numeric',weekday:'short'}).format(new Date());
const shortDate=s=>new Intl.DateTimeFormat('ja-JP',{month:'numeric',day:'numeric'}).format(new Date(s+'T00:00:00+09:00'));
const active=()=>state.settings.locations.filter(x=>x.active!==false);const current=()=>active()[state.index]||active()[0];
function pendingRain(){const today=jpISO();return state.records.find(r=>r.status==='rain_skip'&&r.performedOn<today&&!state.records.some(d=>d.locationId===r.locationId&&d.status==='completed'&&d.createdAt>r.createdAt))}
function chooseNext(){const a=active(),today=jpISO(),done=new Set(state.records.filter(r=>r.performedOn===today&&r.status==='completed').map(r=>r.locationId)),id=pendingRain()?.locationId||a.find(x=>!done.has(x.id))?.id;state.index=Math.max(0,a.findIndex(x=>x.id===id))}
function toast(message){document.body.insertAdjacentHTML('beforeend',`<div class="toast" role="status">✓ ${esc(message)}</div>`);setTimeout(()=>$('.toast')?.remove(),1900)}
function gradient(c){return {green:'linear-gradient(135deg,#e1eadb,#b8cda9)',sand:'linear-gradient(135deg,#f0e5d1,#dac19b)',blue:'linear-gradient(135deg,#dcebf0,#afd0da)',purple:'linear-gradient(135deg,#e9e0ef,#cbbadc)'}[c]}
function home(){const list=active(),loc=current(),today=jpISO(),done=new Set(state.records.filter(r=>r.performedOn===today&&r.status==='completed').map(r=>r.locationId)),last=state.records.find(r=>r.locationId===loc.id&&r.status==='completed'),carry=pendingRain()?.locationId===loc.id;
return `<main class="shell"><header class="top"><div class="brand"><span class="logo">✦</span><div><p class="eyebrow">CLEANING ROTATION</p><h1>今日のお掃除</h1></div></div><div class="top-actions"><span class="device-pill">このiPadに保存</span><span class="date-pill">📅 ${jpDay()}</span><button class="icon-btn" data-action="admin" aria-label="管理画面">⚙</button></div></header>
<section class="card"><div class="card-grid"><div class="main-pane"><div class="location-head"><div><div class="badges"><span class="badge">⌖ ${loc.area}</span>${carry?'<span class="badge rain">☂ 雨天延期から繰り越し</span>':''}</div><h2>${esc(loc.name)}</h2><p class="summary">${esc(loc.summary)}</p></div><div class="last"><small>前回の実施日</small><strong>${last?shortDate(last.performedOn):'記録なし'}</strong>${last?`<span>担当：${esc(last.cleaner)}</span>`:''}</div></div>
<details class="details"><summary>掃除の詳細を見る</summary><div class="detail-body">${loc.photo?`<img class="photo" src="${loc.photo}" alt="${esc(loc.name)}の写真">`:`<div class="photo photo-empty" style="background:${gradient(loc.color)}"><div><div style="font-size:38px">▧</div>${esc(loc.name)}の写真<br><small>管理画面から登録できます</small></div></div>`}<div><div class="info-box"><h3>🧴 使う道具</h3><p>${loc.tools.map(esc).join('、')}</p></div><div class="info-box"><h3>☑ 手順</h3><ol>${loc.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div></div></div></details></div>
<aside class="side-pane"><p class="side-label">担当者を選ぶ</p><div class="people">${state.settings.cleaners.map(n=>`<button class="person ${n===state.cleaner?'selected':''}" data-cleaner="${esc(n)}">${esc(n)} ${n===state.cleaner?'✓':''}</button>`).join('')}</div>${loc.requiresNote?`<div class="note"><label for="note">実施内容（必須）</label><textarea id="note" maxlength="200" placeholder="例：1階の窓とサッシを清掃">${esc(state.note)}</textarea></div>`:''}<button class="complete" data-action="complete" ${loc.requiresNote&&!state.note.trim()?'disabled':''}>✓ 完了する</button>${loc.area==='屋外'?'<button class="rain-btn" data-action="rain">☂ 雨天で延期</button>':''}</aside></div></section>
<div class="pager"><button class="btn" data-action="prev">‹ <span>前の場所</span></button><div class="pager-count">${state.index+1} / ${list.length}</div><button class="btn" data-action="next"><span>次の場所</span> ›</button></div></main>
<nav class="bottom"><div class="bottom-inner"><div class="progress"><small>本日の進み具合</small><strong>${done.size} / ${list.length} か所 完了</strong></div><div class="bottom-actions"><button class="btn history-btn primary" data-action="list">一覧</button><button class="btn history-btn" data-action="history">☷ 履歴</button></div></div></nav>${state.history?historyView():''}${state.daily?dailyView():''}`}
function dailyView(){const today=jpISO(),done=new Set(state.records.filter(r=>r.performedOn===today&&r.status==='completed').map(r=>r.locationId));return `<div class="overlay"><section class="modal daily" role="dialog" aria-modal="true" aria-labelledby="daily-title"><p class="date">${jpDay()}</p><h2 id="daily-title">今日のお掃除一覧</h2><p class="summary">場所をタップして、担当者を選んでください。</p><ul class="daily-list">${active().map((x,i)=>`<li><button class="location-choice" data-location="${i}" aria-label="${esc(x.name)}の担当者を選ぶ"><span>${esc(x.name)}</span><span class="${done.has(x.id)?'done':''}">${done.has(x.id)?'完了 ✓':'未完了　›'}</span></button></li>`).join('')}</ul><button class="btn wide" data-action="close-daily">掃除画面へ戻る</button></section></div>`}
function historyView(){return `<div class="overlay" data-action="close-history"><section class="modal drawer" role="dialog" onclick="event.stopPropagation()"><header class="drawer-head"><h2>お掃除の履歴</h2><p>このiPadに保存されています。</p><button class="icon-btn close" data-action="close-history">×</button></header><div class="drawer-body">${state.records.length?`<button class="btn undo" data-action="undo">↶ 直前の記録を取り消す</button><ol class="history-list">${state.records.map(r=>{const l=state.settings.locations.find(x=>x.id===r.locationId);return `<li><div><p>${esc(l?.name||r.locationId)}</p><small>${shortDate(r.performedOn)}・${esc(r.cleaner)}${r.note?`<br>実施内容：${esc(r.note)}`:''}</small></div><span class="status ${r.status==='rain_skip'?'rain':''}">${r.status==='completed'?'完了':'雨天延期'}</span></li>`}).join('')}</ol>`:'<div class="empty">まだ記録がありません</div>'}</div></section></div>`}
function admin(){return `<main class="shell"><header class="admin-head"><div class="admin-title"><button class="icon-btn" data-action="home">←</button><div><p class="eyebrow">お掃除ローテーション</p><h1>管理画面</h1></div></div><button class="btn primary" data-action="save-settings">変更を保存</button></header>
<section class="admin-section"><h2>従業員</h2><p class="lead">掃除完了時に表示する担当者を設定します。</p><div class="employee-grid">${state.settings.cleaners.map((n,i)=>`<div class="input-row"><input data-employee="${i}" value="${esc(n)}" aria-label="従業員${i+1}"><button class="btn delete" data-remove-employee="${i}" aria-label="削除">×</button></div>`).join('')}</div><button class="btn" data-action="add-employee" style="margin-top:12px">＋ 従業員を追加</button></section>
<section class="admin-section"><h2>掃除項目</h2><p class="lead">表示順、説明、道具、手順、写真を変更できます。</p>${state.settings.locations.map((l,i)=>`<details class="admin-item"><summary>${i+1}　${esc(l.name)}　<span class="badge">${l.active===false?'非表示':l.area}</span></summary><div class="admin-item-body"><div class="mini-actions"><button class="btn" data-move="${i},-1" ${i===0?'disabled':''}>↑ 上へ</button><button class="btn" data-move="${i},1" ${i===state.settings.locations.length-1?'disabled':''}>↓ 下へ</button><button class="btn" data-toggle="${i}">${l.active===false?'表示する':'非表示にする'}</button></div><div class="field-grid"><label class="field">項目名<input data-field="${i},name" value="${esc(l.name)}"></label><label class="field">区分<select data-field="${i},area"><option ${l.area==='室内'?'selected':''}>室内</option><option ${l.area==='屋外'?'selected':''}>屋外</option></select></label><label class="field full">説明<input data-field="${i},summary" value="${esc(l.summary)}"></label><label class="field">使う道具（1行に1つ）<textarea data-field="${i},tools">${esc(l.tools.join('\n'))}</textarea></label><label class="field">手順（1行に1手順）<textarea data-field="${i},steps">${esc(l.steps.join('\n'))}</textarea></label></div><label class="field" style="display:block;margin-top:14px"><input type="checkbox" data-required="${i}" ${l.requiresNote?'checked':''} style="width:auto"> 完了時に実施内容を必須にする</label><div style="margin-top:16px"><strong>場所写真</strong>${l.photo?`<img class="photo-preview" src="${l.photo}" alt="登録写真">`:''}<p><label class="btn primary" style="display:inline-flex;align-items:center">写真を${l.photo?'変更':'登録'}<input class="hidden" type="file" accept="image/*" data-photo="${i}"></label>${l.photo?` <button class="btn" data-remove-photo="${i}">写真を外す</button>`:''}</p><p class="hint">写真はこのiPad内だけに保存されます。</p></div></div></details>`).join('')}</section>
<section class="admin-section"><h2>バックアップ</h2><p class="lead">iPadの故障やWebサイトデータ削除に備えて、定期的に保存してください。</p><div class="storage-actions"><button class="btn primary" data-action="export">バックアップを書き出す</button><label class="btn" style="display:grid;place-items:center">バックアップから復元<input class="hidden" type="file" accept="application/json" id="import-file"></label><button class="btn danger" data-action="clear-records">履歴をすべて消去</button><button class="btn" data-action="reset-settings">初期設定に戻す</button></div></section><div class="savebar"><button class="btn primary" data-action="save-settings">変更を保存</button></div></main>`}
function render(){const adminMode=location.hash==='#/admin';$('#app').innerHTML=adminMode?admin():home();bind();document.querySelectorAll('[data-location]').forEach(button=>button.onclick=()=>{state.index=Number(button.dataset.location);state.note='';state.daily=false;render();const person=$('.person');person?.focus({preventScroll:true});$('.side-pane')?.scrollIntoView({behavior:'smooth',block:'nearest'})});const listButton=$('[data-action="list"]');if(listButton)listButton.onclick=()=>{state.history=false;state.daily=true;render()}}
function bind(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));document.querySelectorAll('[data-cleaner]').forEach(b=>b.onclick=()=>{state.cleaner=b.dataset.cleaner;render()});$('#note')?.addEventListener('input',e=>{state.note=e.target.value;$('.complete').disabled=!state.note.trim()});document.querySelectorAll('[data-employee]').forEach(e=>e.oninput=()=>state.settings.cleaners[+e.dataset.employee]=e.value);document.querySelectorAll('[data-remove-employee]').forEach(b=>b.onclick=()=>{if(state.settings.cleaners.length>1){state.settings.cleaners.splice(+b.dataset.removeEmployee,1);render()}});document.querySelectorAll('[data-field]').forEach(e=>e.oninput=()=>{const[i,k]=e.dataset.field.split(',');state.settings.locations[+i][k]=k==='tools'||k==='steps'?e.value.split('\n').filter(Boolean):e.value});document.querySelectorAll('[data-required]').forEach(e=>e.onchange=()=>state.settings.locations[+e.dataset.required].requiresNote=e.checked);document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const l=state.settings.locations[+b.dataset.toggle];l.active=l.active===false;render()});document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const[i,d]=b.dataset.move.split(',').map(Number),a=state.settings.locations,x=a.splice(i,1)[0];a.splice(i+d,0,x);render()});document.querySelectorAll('[data-photo]').forEach(e=>e.onchange=async()=>{if(e.files[0]){state.settings.locations[+e.dataset.photo].photo=await resizeImage(e.files[0]);render()}});document.querySelectorAll('[data-remove-photo]').forEach(b=>b.onclick=()=>{delete state.settings.locations[+b.dataset.removePhoto].photo;render()});$('#import-file')?.addEventListener('change',importBackup)}
async function action(a){const list=active();if(a==='prev'){state.index=(state.index-1+list.length)%list.length;state.note='';render()}if(a==='next'){state.index=(state.index+1)%list.length;state.note='';render()}if(a==='history'){state.history=true;render()}if(a==='close-history'){state.history=false;render()}if(a==='close-daily'){state.daily=false;render()}if(a==='admin'){location.hash='#/admin'}if(a==='home'){location.hash=''}if(a==='complete')await addRecord('completed');if(a==='rain')await addRecord('rain_skip');if(a==='undo')await undo();if(a==='add-employee'){state.settings.cleaners.push('新しい従業員');render()}if(a==='save-settings'){state.settings.cleaners=state.settings.cleaners.map(x=>x.trim()).filter(Boolean);if(!state.settings.cleaners.length)return toast('従業員を1名以上入力してください');await dbSet(SETTINGS_KEY,state.settings);state.cleaner=state.settings.cleaners.includes(state.cleaner)?state.cleaner:state.settings.cleaners[0];toast('設定をこのiPadに保存しました')}if(a==='export')exportBackup();if(a==='clear-records'&&confirm('履歴をすべて消去しますか？この操作は取り消せません。')){state.records=[];await dbSet(RECORDS_KEY,[]);toast('履歴を消去しました')}if(a==='reset-settings'&&confirm('従業員と掃除項目を初期設定に戻しますか？')){state.settings=structuredClone(DEFAULTS);await dbSet(SETTINGS_KEY,state.settings);render();toast('初期設定に戻しました')}}
async function addRecord(status){const loc=current(),today=jpISO();if(status==='completed'&&state.records.some(r=>r.locationId===loc.id&&r.status==='completed'&&r.performedOn===today)&&!confirm(`${loc.name}は本日すでに完了しています。\n重複して記録しますか？`))return;if(status==='completed'&&loc.requiresNote&&!state.note.trim())return toast('実施内容を入力してください');const rec={id:Date.now(),locationId:loc.id,cleaner:state.cleaner,status,note:state.note.trim()||null,performedOn:jpISO(),createdAt:new Date().toISOString(),displayTime:jpNow()};state.records.unshift(rec);await dbSet(RECORDS_KEY,state.records);toast(status==='completed'?`${loc.name}を完了しました`:`${loc.name}を雨天延期しました`);state.note='';setTimeout(()=>{state.index=(state.index+1)%active().length;render()},700)}
async function undo(){const r=state.records[0];if(!r)return;const l=state.settings.locations.find(x=>x.id===r.locationId);if(!confirm(`直前の記録「${l?.name||r.locationId}・${r.cleaner}」を取り消しますか？`))return;state.records.shift();await dbSet(RECORDS_KEY,state.records);state.history=false;state.index=Math.max(0,active().findIndex(x=>x.id===r.locationId));render();toast('直前の記録を取り消しました')}
function resizeImage(file){return new Promise((ok,no)=>{const r=new FileReader;r.onerror=()=>no(r.error);r.onload=()=>{const img=new Image;img.onload=()=>{const max=1280,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);ok(c.toDataURL('image/jpeg',.82))};img.onerror=no;img.src=r.result};r.readAsDataURL(file)})}
function exportBackup(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),settings:state.settings,records:state.records},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`osouji-backup-${jpISO()}.json`;a.click();URL.revokeObjectURL(a.href);toast('バックアップを書き出しました')}
async function importBackup(e){try{const data=JSON.parse(await e.target.files[0].text());if(!data.settings?.cleaners||!Array.isArray(data.records))throw Error();if(!confirm('現在の設定と履歴をバックアップの内容に置き換えますか？'))return;state.settings=data.settings;state.records=data.records;await dbSet(SETTINGS_KEY,state.settings);await dbSet(RECORDS_KEY,state.records);render();toast('バックアップを復元しました')}catch{toast('バックアップファイルを読み込めませんでした')}}
addEventListener('hashchange',render);(async()=>{try{state.settings=await dbGet(SETTINGS_KEY)||structuredClone(DEFAULTS);state.records=await dbGet(RECORDS_KEY)||[];state.cleaner=state.settings.cleaners[0];chooseNext();render()}catch(e){console.error(e);$('#app').innerHTML='<div class="loading">端末内の保存領域を利用できません。Safariの設定をご確認ください。</div>'}})();
